### ISSUE TITLE
Create Database Schema

### ISSUE THREAD

**Issue by fepersembe** [bounswe/bounswe2016group12#71]
Database schema must be generated

**Comment by ThoAppelsin** [comment]
The schema can be found at: https://github.com/bounswe/bounswe2016group12/wiki/Database-Schema

Here's what I've judged to be;
- Wrong:
  - There is a field named `reply_count` under `topic`, but we have "comments" in our glossary, not "replies".
  - Similarly, we have "comments", not "posts", hence the name for the type `post` should be replaced with `comment`. So should the `topic_post` be `topic_comment` and the field `post_id` within be `comment_id`.
  - Word "first" is misspelled in the field `firts_topic_id` on the type `relation`.
- Missing:
  - Our comments are required to be editable. Moreover, each version of an edited comment should be kept safe, since it is required that a user can view the previous versions if he/she wants (check [**1.6.2.1.**](https://github.com/bounswe/bounswe2016group12/wiki/Requirements#16-viewing-requirements)). To fix this:
    - We shall introduce another type `comment_version` with the following fields:
      - `content` as varchar for its content on that version,
      - `upvote_count` and `downvote_count` as integers for the number of up/downvotes it received while it was in that version,
      - `date` as datetime for the date when that version was submitted,
      - finally `id` as the integer key as its order on the version history.
    - We shall leave out all the fields in the `comment` type, but its ID of course.
    - We shall introduce another relational type `comment_comment_version` with its obvious three fields:
      - `id` as the integer key,
      - `comment_id` as the integer key for the related comment,
      - `comment_version_id` as the integer key for the related comment version.
  - We need to include a boolean field on the `relation` type and call it `symmetric`, since our relations can be symmetric or directed.

Other than that, I think we need some sort of revision on the tag types that we can talk together.

**Comment by fepersembe** [comment]
Revisions in the Meeting #11 will be applied.

**Comment by fepersembe** [comment]
Changes listed are DONE!
